# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pnpm" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
  
  # Check for GitHub Actions updates (optional, if you use GitHub Actions)
  - package-ecosystem: "github-actions"
    directory: "/" # Adjust if your GitHub Actions are in a subdirectory
    schedule:
      interval: "weekly"
