name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run lint
      run: pnpm run lint

    - name: Get next version
      run: npx semantic-release --dry-run
      id: get-next-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set version
      run: node update-version.mjs ${{ steps.get-next-version.outputs.new-release-version }}

    - name: Build application
      run: pnpm run build

    - name: Test
      run: pnpm run test:ci

    - name: Upload dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: dist/prompt-polish/browser

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage/prompt-polish/lcov.info
        flags: unittests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run e2e tests
      run: pnpm run e2e
